meta_product_name: "Whiskit"
meta_title: "Whiskit - Home-cooked food. Shared locally"

meta_description: "Young professionals that dislike cooking after a long day at work, yet still want to eat healthily and not pay for take-aways every night"
meta_image: "whiskit.jpg" # should exist in `app/assets/images/`
